build:
	gcc \
	-Wfatal-errors \
	-std=c99 \
	./*.c \
	-I"D:\\Gautam\\libsdl\\include" \
	-L"D:\\Gautam\\libsdl\\lib" \
	-lmingw32 \
	-lSDL2main \
	-lSDL2 \
	-o renderer.exe

run:
	renderer.exe

clean:
	del renderer.exe